# Generated by Django 5.1 on 2024-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='youtube',
            field=models.URLField(blank=True, max_length=125, null=True),
        ),
    ]
