# Generated by Django 5.1 on 2024-08-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.SlugField()),
                ('phone', models.ImageField(blank=True, null=True, upload_to='myport/%Y/%m/%d')),
                ('email', models.IntegerField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, max_length=225, null=True)),
                ('facebook', models.URLField(blank=True, max_length=225, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=225, null=True)),
                ('youtube', models.URLField(blank=True, max_length=225, null=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
