# Generated by Django 5.1 on 2024-08-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name': 'email', 'verbose_name_plural': 'emails'},
        ),
    ]
