# Generated by Django 5.1 on 2024-08-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('slug', models.CharField(max_length=125)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('master_chefs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
            },
        ),
    ]
