# Generated by Django 5.1 on 2024-08-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_content_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
