# Generated by Django 5.1 on 2024-08-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
