# Generated by Django 5.1 on 2024-08-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_rename_content_reservation_special_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='num_of_people',
            new_name='no_of_people',
        ),
    ]
