# Generated by Django 5.1 on 2024-08-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_rename_num_of_people_reservation_no_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, default=0, max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(blank=True, default=0, max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='no_of_people',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_request',
            field=models.CharField(blank=True, default=0, max_length=225),
            preserve_default=False,
        ),
    ]
